config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  # get 'static_pages/home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

  # For details on the DSL available within this file, 
  # see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "hello, world!"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + "|" + base_title
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--ページ上部の要素 3つのCSSクラスを与えている-->
<!--navbarクラスはBoostrapで特別な意味を持つ-->
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!--埋め込みRailsコード-->
    <!--Railsヘルパーの link_to 第一引数:リンクテキスト, 第二引数:URL('#でダミー'), 第三引数:オプションハッシュ CSS id logoを指定-->
    <%= link_to "sample app", root_path, id: "logo" %>
    <!--navタグはその内側がナビゲーションリンクであることを意図している -->
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",  help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<!--第一引数の'application'はスタイルシートへのパス、最後の引数のハッシュの{}は省略される-->
<!--第二引数のハッシュ値はメディアタイプ要素とturbolinks機能をオンにする要素から構成されている-->
<%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %> 
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <!--partialの表現(app/views/layouts/_hogehogeファイル)-->
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <!--'render' Railsヘルパー呼び出し-->
    <%= render 'layouts/header' %>
    <!--メインコンテンツ用のdiv-->
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href = "https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  is a <a href = "https://railstutorial.jp/#ebook">book</a> and
  <a href = "https://railstutorial.jp/#screencast">screencast</a>
  to teach web development with
  <a href = "https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href = "https://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<!--<% provide(:title, "Help") %>-->
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href = "https://railstutorial.jp/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href = "https://railstutorial.jp/#ebook">
  <em>Ruby on Rails Tutorial</em>book</a>
</p>

app/views/static_pages/home.html.erb
<!--<% provide(:title, "Home") %>-->
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  
  <h2>
    This is the home page for the
    <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<!--引数に画像ファイルのパスと任意のオプションハッシュをとるimage_tagヘルパーの能力が示されている-->
<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org/' %>
<!--<%= link_to image_tag("kitten.jpg", alt: "home image") %> -->
>>>>>>> filling-in-layout

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>